### ISSUE TITLE
Error in using default kernel

### ISSUE THREAD

**Issue by rrpastro** [OxES/k2sc#15]
I get the following error message while I am trying to use an ASCII file that is not supported by python3 but supported by python2, and default kernel. 

'''''
INFO Worker 0 <248442470>: Starting Lomb-Scargle period search
INFO Worker 0 <248442470>:   Using SqrExp position kernel
INFO Worker 0 <248442470>:   Found periodicity p =    0.24 (fap 3.9367e-139 < 1e-50), will use a quasiperiodic kernel
INFO Worker 0 <248442470>: Starting global hyperparameter optimisation using DE
Traceback (most recent call last):
  File "/anaconda3/envs/py27/bin/k2sc", line 4, in <module>
    __import__('pkg_resources').run_script('K2SC==0.8', 'k2sc')
  File "/anaconda3/envs/py27/lib/python2.7/site-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/anaconda3/envs/py27/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1524, in run_script
    exec(script_code, namespace, namespace)
  File "/anaconda3/envs/py27/lib/python2.7/site-packages/K2SC-0.8-py2.7.egg/EGG-INFO/scripts/k2sc", line 411, in <module>

  File "/anaconda3/envs/py27/lib/python2.7/site-packages/K2SC-0.8-py2.7.egg/EGG-INFO/scripts/k2sc", line 219, in detrend

  File "build/bdist.macosx-10.6-x86_64/egg/k2sc/de.py", line 110, in __call__
  File "build/bdist.macosx-10.6-x86_64/egg/k2sc/detrender.py", line 57, in neglnposterior
  File "build/bdist.macosx-10.6-x86_64/egg/k2sc/gp.py", line 131, in lnlikelihood
  File "build/bdist.macosx-10.6-x86_64/egg/k2sc/gp.py", line 84, in compute
  File "/anaconda3/envs/py27/lib/python2.7/site-packages/scipy/linalg/decomp_cholesky.py", line 132, in cho_factor
    check_finite=check_finite)
  File "/anaconda3/envs/py27/lib/python2.7/site-packages/scipy/linalg/decomp_cholesky.py", line 30, in _cholesky
    raise LinAlgError("%d-th leading minor not positive definite" % info)
numpy.linalg.linalg.LinAlgError: 4-th leading minor not positive definite
''''''
I don't get any error if I use basic kernel but this means I am restricting the cases where there are periodic features and quasi-periodic features.

**Comment by saigrain** [comment]
This is not a bug, exactly. The error occurs when the code attempts to evaluate the likelihood of the GP model and the covariance matrix is ill-conditioned (and hence cannot be inverted without large numerical errors). One easy way to fix that problem is to artificially increase the formal uncertainties in your input file. Can you try doing that and see if it fixes the problem?

**Comment by rrpastro** [comment]
I changed the errors in flux values to 10*np.sqrt(flux) but still I can see the same problem. 

Here are some lines of my ASCII file:
'''
Dates Cadences Flux1 Uncert1 Xpos Ypos Quality
3072.72870042 145045 595.76412697 244.08279885 610.79639 775.54480 524288
3072.74913296 145046 600.84801035 245.12201255 610.70644 775.56774 0
3072.76956550 145047 588.15472058 242.51901381 610.64158 775.58440 0
3072.78999815 145048 592.47314689 243.40771288 610.58304 775.62371 0
3072.81043059 145049 596.33847980 244.20042584 610.50611 775.64645 0
3072.83086313 145050 595.35398818 243.99876807 610.44960 775.67590 0
3072.85129567 145051 599.34298764 244.81482546 610.39479 775.70505 0
3072.87172821 145052 597.35251292 244.40796078 610.33183 775.74779 0
3072.89216075 145053 598.82663811 244.70934557 610.27831 775.79942 0
3072.91259329 145054 595.56503989 244.04201275 610.22121 775.84784 0
'''

I am not sure if I did the same thing as Suzanne has suggested above. Would you please suggest what else I can check.

**Comment by hpparvi** [comment]
I've added a quick patch that should fix the issue for now. The neglnposterior method in Detrender now returns inf if the covariance matrix inversion fails.

**Comment by rrampall** [comment]
Hi, 
I'm having the same linear algebra error when running k2sc on K2 C16 light curves. It has happened 8 times on the 585 light curves I've processed (so not a huge problem) but was wondering if there was a solution? Thanks!
