### ISSUE TITLE
Problem in _define_kernel

### ISSUE THREAD

**Issue by hposborn** [OxES/k2sc#3]
I get the same bug when k2sc tries to define kernels on both Linux and Mac (and with all required packages installed):

```
Traceback (most recent call last):
  File "./k2sc", line 387, in <module>
    detrend(dataset)
  File "./k2sc", line 119, in detrend
    splits=splits, kernel=BasicKernelEP(),
  File "/home/astro/phrnbe/.local/lib/python2.7/site-packages/k2sc/kernels.py", line 44, in __init__
    self._define_kernel()
  File "/home/astro/phrnbe/.local/lib/python2.7/site-packages/k2sc/kernels.py", line 122, in _define_kernel
    self._k1 = pv[0] * ESK(1/pv[1], ndim=3, dim=0)
TypeError: __init__() got an unexpected keyword argument 'dim'
```

**Comment by hposborn** [comment]
Problem fixed - my version of george (1.0-dev) has dropped the 'dim' argument from the ExpSquared kernel. Might be nice to update it to 1.0 capability as I imagine that'll take over george-0.2 very soon though.
